# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				donkey = true
				cow = true
				pig = true
				pillager = true
				skeleton = true
				iron_golem = true
				llama = true
				bat = true
				cat = true
				rabbit = true
				zombie = true
				armor_stand = true
				sheep = true
				player = true
				item = true
				villager = true
				salmon = true
				zombie_villager = true
				horse = true
				cave_spider = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				nightmare = true

			[light_sources.settings.entities.biomemakeover]
				scuttler = true
				tumbleweed = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_skeleton = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.artifacts]
				mimic = true

